from __future__ import annotations

from collections.abc import Iterable
from typing import Any

# ruff: noqa: N801

__version__: str

class device:
    def __init__(self, type: object | None = ..., index: int | None = ...) -> None: ...
    def __str__(self) -> str: ...
    type: str

class Tensor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def to(self, device: device | str) -> Tensor: ...
    def numel(self) -> int: ...
    def argmax(self, dim: int | None = ..., keepdim: bool = ...) -> Tensor: ...
    def flatten(self, start_dim: int = ..., end_dim: int = ...) -> Tensor: ...
    def item(self) -> Any: ...
    def tolist(self) -> list[Any]: ...

def manual_seed(seed: int) -> None: ...
def randn(*shape: Any, **kwargs: Any) -> Tensor: ...
def randperm(n: int, generator: Any | None = ...) -> Tensor: ...
def tensor(data: Any, device: Any | None = ...) -> Tensor: ...

class _CudaModule:
    def is_available(self) -> bool: ...
    def device_count(self) -> int: ...

cuda: _CudaModule

class _VersionModule:
    cuda: str | None

version: _VersionModule

class Module:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def parameters(self) -> Iterable[Tensor]: ...
    def train(self, mode: bool = ...) -> Module: ...
    def eval(self) -> Module: ...
    def to(self, device: device | str) -> Module: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class Optimizer:
    def zero_grad(self) -> None: ...
    def step(self) -> None: ...

class _OptimNamespace:
    class Adam(Optimizer):
        def __init__(
            self, params: Iterable[Any], lr: float | None = ..., **kwargs: Any
        ) -> None: ...

    class AdamW(Optimizer):
        def __init__(
            self, params: Iterable[Any], lr: float | None = ..., **kwargs: Any
        ) -> None: ...

optim = _OptimNamespace()

class Generator:
    def manual_seed(self, seed: int) -> None: ...

class _NoGrad:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

def no_grad() -> _NoGrad: ...
def save(obj: Any, f: Any, **kwargs: Any) -> None: ...
def load(f: Any, map_location: Any | None = ...) -> Any: ...

nn: Any
utils: Any
data: Any
tensorboard: Any
