from __future__ import annotations

from typing import Any

class SummaryWriter:
    def __init__(self, log_dir: str | None = ..., **kwargs: Any) -> None: ...
    def add_scalar(
        self, tag: str, scalar_value: float | int, global_step: int | None = ...
    ) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
