from __future__ import annotations

from collections.abc import Callable, Iterable

class Resize:
    def __init__(self, size: tuple[int, int]) -> None: ...
    def __call__(self, img: object) -> object: ...

class Grayscale:
    def __init__(self, num_output_channels: int = 1) -> None: ...
    def __call__(self, img: object) -> object: ...

class ToTensor:
    def __call__(self, img: object) -> object: ...

class Normalize:
    def __init__(
        self,
        mean: tuple[float, float, float],
        std: tuple[float, float, float],
        inplace: bool = False,
    ) -> None: ...
    def __call__(self, tensor: object) -> object: ...

class Compose:
    def __init__(self, transforms: Iterable[Callable[[object], object]]) -> None: ...
    def __call__(self, img: object) -> object: ...
