from __future__ import annotations

from typing import Any

def apply_chunking_to_forward(*args: Any, **kwargs: Any) -> Any: ...
def find_pruneable_heads_and_indices(*args: Any, **kwargs: Any) -> Any: ...
def prune_linear_layer(*args: Any, **kwargs: Any) -> Any: ...
